[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/book"
  to = "https://hotels.cloudbeds.com/reservation/lWSPnI"
  status = 302

[[redirects]]
  from = "/book-now"
  to = "https://hotels.cloudbeds.com/reservation/lWSPnI"
  status = 302

[[redirects]]
  from = "/reservation"
  to = "https://hotels.cloudbeds.com/reservation/lWSPnI"
  status = 302